version: 1.0.{build}
branches:
  only:
  - nuget
build_script:
- cmd: >-
    nuget restore

    MSBuild .\build.proj /t:NightlyBuild /verbosity:diag /p:BuildLastMajorVersion=0.0.0 /p:BuildVersion=0.0.1 /p:NuGetPrerelease=true
artifacts:
- path: build\bin\Release\NuGetPackages
  name: NuGet